### PR TITLE
Reduce script duplication

### PR DESCRIPTION
**Pull request by christopher-dG**
I am not 100% sure if this works yet. I need to test it, especially whether or not this works with extra user-defined `variables`.
But I thought that this would be a nice change to not have the same script written 6 times 🙂. The script has been simplified slightly, too.

I've also removed 0.7, since I  don't think it's reasonable to still be testing on that.

...But now that I look at https://gitlab.com/gitlab-org/gitlab/issues/16343, I am pretty sure that the variables thing will not work properly... but we'll see if I can find some kind of workaround.

### CODE REVIEW

**Comment by christopher-dG** [comment]
Alright, this does work now, although I don't like it as much as I did before. But maybe it's still an improvement.

**Comment by maleadt** [comment]
We could probably use some CI over here, e.g. installing and testing the Example package, if we're going to be relying on these templates more extensively.

Why not put the `apt` invocations in the script too? I've always wanted to try and avoid those, since it's a significant latency penalty before starting tests, but Pkg really wants wget/curl/...

**Comment by christopher-dG** [comment]
Adding some kind of test is a good idea. As for the `curl` installation, we need it or `wget`/etc. to download the script... rather unfortunate.

**Comment by christopher-dG** [comment]
Added some testing of the `install_julia.sh` script, gotta think about how best to simulate an actual test run.

**Comment by christopher-dG** [comment]
Got a test in that actually runs tests. What are your thoughts on converting the `.julia:X.Y` definitions into a single `.install` where the user can set a `JULIA_VERSION` variable? Obviously that would involve changing the template to v7.

Using it would look like this:

```yml
include: https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v7.yml

LTS:
  extends:
    - .install
    - .test
  variables:
    JULIA_VERSION: '1.0'

Stable:
  extends: 
    - .install
    - .test
  # Omit the JULIA_VERSION here, it defaults to latest stable (1.x).

Nightly:
  extends:
    - .install
    - .test
  variables:
    JULIA_VERSION: nightly

Master:
  extends:
    - .install
    - .test
  variables:
    JULIA_VERSION: master
```

While in our `v7.yml`, we would no longer need to have separate definitions for each Julia version. We could basically put what's in `install_julia.sh` in `before_script`.

**Comment by maleadt** [comment]
I prefer not using environment variables because they don't compose well (you easily overwrite them), and IMO `extends: julia:1.4` looks clearer to me than `extends: julia` && `variables: JULIA_VERSION='1.4'`. Duplication at the template's end is hidden from the user anyway, or do you have other reasons to prefer this set-up?

**Comment by maleadt** [comment]
> Got a test in that actually runs tests.

We'll need bors to test this for outside PRs, but I'll make you a collaborator so that you can push branches here.

**Comment by christopher-dG** [comment]
No big reason for wanting to change it, it mostly just seemed easier to maintain in this repo. But since it's hidden from the user either way, it doesn't matter much!

**Comment by christopher-dG** [comment]
I think this repo will need to be added to the GitLab org as well?

**Comment by christopher-dG** [comment]
replaced by #20

**Pull request closed without merging**
