### PR TITLE
Revert breaking change to JULIA_PROJECT.

### PR DESCRIPTION
**Pull request by maleadt**
@christopher-dG Why did you add the change to JULIA_PROJECT? That wasn't there before the refactor. It broke some packages, e.g. https://gitlab.com/JuliaGPU/GPUCompiler.jl/-/jobs/612598721

### CODE REVIEW

**Comment by maleadt** [comment]
I guess you did that to remove `--project`, but that's a change in behavior, so better leave it out? Unless you had a specific reason to prefer `JULIA_PROJECT` over `--project`, of course.

**Comment by christopher-dG** [comment]
Correct, I was just trying to avoid having to pass `--project` to every Julia invocation --- I didn't anticipate this changing any behaviour, sorry! The test will need to be updated (maybe `cd` to the Example dir would work, or `mv` everything from Example to `.` if not) but other than that this is good.

**Comment by maleadt** [comment]
Something's still wrong with the link to gitlab: the github webhook that informs gitlab about a push gets error denied.

**Comment by christopher-dG** [comment]
I've noticed that it's kind of finnicky on other repos too. I think all that's to be done is to replace the token here: https://gitlab.com/JuliaGPU/gitlab-ci/-/services/github/edit

**Comment by maleadt** [comment]
> I've noticed that it's kind of finnicky on other repos too. I think all that's to be done is to replace the token here: https://gitlab.com/JuliaGPU/gitlab-ci/-/services/github/edit

No, that's the GitHub token to report back. It's the other direction that fails here. I've already tried replacing it with my personal GitLab token (in the GitHub webhook settings), but I suspect something went wrong when setting-up the mirror.

**Comment by christopher-dG** [comment]
Ah, I see. When I set up the mirror I used just the URL rather than a token because I didn't have permissions on this repo at the time, but I think you fixed that earlier.

**Comment by maleadt** [comment]
We'll probably have to recreate the mirror, but nowadays there's a 7-day wait time until GitLab actually deletes the repo mirror so I'm not sure how that would work. Can try after we get the most important things fixed here.

**Pull request merged**
